version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: wpdb
    volumes:
      - /home/rohith/wordpressdb/:/var/lib/mysql
    networks:
      - wordpressnetwork
  wordpress:
    image: rohith6282/wordpress:latest
    container_name: wordpress
    ports:
      - "8080:8080"
    volumes:
      - /home/rohith/wordpress/wp-config.php:/var/www/html/wp-config.php
    networks:
      - wordpressnetwork
    depends_on:
      - db

  nginx:
    image: rohith6282/job26nginx:latest2
    container_name: nginx
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - /home/rohith/nginx/nginx.conf:/opt/nginx/conf/nginx.conf
      - /home/rohith/nginx/ssl/server.key:/opt/nginx/ssl/server.key
      - /home/rohith/nginx/ssl/server.crt:/opt/nginx/ssl/server.crt

    networks:
      - wordpressnetwork
    depends_on:
      - wordpress


networks:
  wordpressnetwork:
    driver: bridge
